### ISSUE TITLE
Selecting Text in shadowroot does not work with button elements

### ISSUE THREAD

**Issue by Peter-Kang** [Tram-One/tram-lite#60] opened 2023-11-17 05:06 UTC
## Summary
When making a custom web component with tram-lite, if there is a button visible near text. The text is no longer selectable. 

If the button has style='display:none' the text is selectable.

Tram-lite example where selecting text is broken:
https://codepen.io/JRJurman/pen/BaMJoVY

Vanilla Web-Component, showing expected text-selection:
https://codepen.io/JRJurman/pen/yLZpYZr

**Comment by JRJurman** [comment] 2023-11-17 23:34
Testing this locally, it doesn't appear to be an issue on Firefox and Safari, only in Chrome and Edge 🤔

**Comment by JRJurman** [comment] 2023-11-18 00:02
Okay, this appears to be a side-effect of having added `delegatesFocus` when creating the shadowRoot: https://codepen.io/JRJurman/pen/bGzamqd

From the documentation, this could be interpreted as correct, although certainly is unexpected.
> If true, **when a non-focusable part of the shadow DOM is clicked**, or .focus() is called on the host element, **the first focusable part is given focus**, and the shadow host is given any available :focus styling.

I'll ask if this is expected behavior, and we can determine where to go from there. 

Potentially we could expose an API to set whether `delegatesFocus` should be true or not, but I'd really like to avoid complicating the API for making elements.

Alternatively, it is possible to fix the selection behavior by making text elements focusable (specifically by giving them a tabindex) - see https://codepen.io/JRJurman/pen/MWLrPom

**Comment by JRJurman** [comment] 2023-11-19 21:16
Okay, this is a potentially unknown issue with the implementation of `delegatesFocus` in chrome. I've created a test for this behavior, and we'll see what the follow-up is: https://github.com/web-platform-tests/wpt/pull/43244

**Comment by JRJurman** [comment] 2023-11-29 17:34
Turns out this is a documented bug: https://crbug.com/950357
Since this is not an issue in Tram-Lite, I'll be closing this as a won't fix. Based on the discussion in the above PR for wpt, it sounds like this is on their radar.

**Closed as not planned by JRJurman** 2023-11-29 17:34 UTC
